packages:
  - "scripts/**"

catalog:
  # Dependencies.
  "@aptos-labs/aptos-client": "^0.1.0"
  "@aptos-labs/ts-sdk": "^1.38.0"
  "@fastify/multipart": "^8.3.1"
  "@fastify/postgres": "^5.2.2"
  "@fastify/static": "^7.0.4"
  "@fastify/swagger": "^8.14.0"
  "@google-cloud/recaptcha-enterprise": "^5.13.0"
  "@google-cloud/secret-manager": "^5.6.0"
  "@irys/sdk": "0.2.9"
  "@noble/hashes": "^1.4.0"
  "@scalar/fastify-api-reference": "^1.24.49"
  "@turnkey/crypto": "^0.2.0"
  "@turnkey/sdk-server": "^0.2.0"
  "@types/node-cron": "^3.0.11"
  "axios": "^1.6.8"
  "async-mutex": "^0.5.0"
  "clipanion": "^4.0.0-rc.4"
  "dotenv": "^16.4.5"
  "fastify": "^4.27.0"
  "fastify-metrics": "^12.1.0"
  "fastify-multipart": "^5.4.0"
  "fastify-type-provider-zod": "^1.2.0"
  "fastify-zod": "^1.4.0"
  "http-errors": "^2.0.0"
  "ioredis": "^5.4.1"
  "libsodium-wrappers": "^0.7.13"
  "lru-cache": "^11.0.2"
  "node-cron": "^3.0.3"
  "node-pg-migrate": "^7.5.1"
  "pg": "^8.12.0"
  "pino": "^9.5.0"
  "pino-http": "^10.1.0"
  "prom-client": "^15.1.3"
  "typescript": "^5.4.3"
  "uuid": "^9.0.1"
  "zod": "^3.23.8"
  "zod-to-json-schema": "^3.23.0"

  # Dev dependencies.
  "@hey-api/client-fetch": "=0.4.2"
  "@hey-api/openapi-ts": "=0.53.11"
  "@types/http-errors": "^2.0.4"
  "@types/libsodium-wrappers": "^0.7.13"
  "@types/node": "^20.14.8"
  "@types/pg": "^8.11.6"
  "@types/uuid": "^9.0.8"
  "lint-staged": "^15.2.7"
  "nodemon": "^3.1.0"
  "pino-pretty": "^13.0.0"
  "prettier": "^3.2.5"
  "prettier-eslint": "^16.1.2"
  "prettier-plugin-sh": "^0.14.0"
  "ts-add-js-extension": "^1.6.5"
  "tsx": "^4.19.3"
  "vitest": "^2.1.8"
